name: Solar System Workflow
on:
  workflow_dispatch: 
  push: 
    branches: ['main', 'feature/*']
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    Unit-Testing:
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        strategy:
          matrix:
            os: [ubuntu-latest]
            version: [18,19]
            exclude:
              - version: '19'
        name: Unit-Testing
        runs-on: '${{matrix.os}}'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node Install
              uses: actions/setup-node@v4
              with:
                node-version: '${{matrix.version}}'

            - name: Caching the previous dependencies
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{runner.os}}_node_modules_${{hashFiles('package-lock.json')}}

            - name: Install dependence
              run: npm install

            - name: Unit Testing
              id: unit-testing
              run: npm test

            - name: Archeiving the artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: mocha-test-result
                overwrite: true
                path: test-results.xml

    code-coverage:
        name: Code-Coverage
        container: 
          image: node:20
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options: 
              --name mongo
        env:
          MONGO_URI: 'mongodb://mongo:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # - name: Node Install
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: 18

            - name: Caching the previous dependencies
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{runner.os}}_node_modules_${{hashFiles('packages-lock.json')}}

            - name: Install dependence
              run: npm install

            - name: Check code Coverage
              run: npm run coverage
              continue-on-error: true

            - name: Archeiving the artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: code-coverage-result
                path: coverage
                overwrite: true
                retention-days: 5

    Docker:
        name: Containerization
        needs: [Unit-Testing, code-coverage]
        permissions: 
          packages: write
        runs-on: ubuntu-latesT
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: GHCR Login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.repository_owner}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Docker build for testing
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github['sha']}}

            - name: Docker image testing
              run: |
                docker images
                docker run --name=ss-app -d \
                  -p 3000:3000 \
                  -e MONGO_URI=$MONGO_URI \
                  -e MONGO_USERNAME=$MONGO_USERNAME \
                  -e MONGO_PASSWORD=$MONGO_PASSWORD \
                  ${{vars.DOCKERHUB_USERNAME}}/solar-system:${GITHUB_SHA}


                export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ss-app)
                echo $IP

                echo "Testing Image url using wget"
                wget -q -O - 127.0.0.1:3000/live | grep -i 'live'

            - name: Container Registry push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                  ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github['sha']}}
                  ghcr.io/${{github.repository_owner}}/solar-system:${{github['sha']}}


    Dev-k8s-deploy:
      name: DEV-K8S-Deployment
      needs: [Docker]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: KUBECTL CLI
            uses: azure/setup-kubectl@v4
            with:
              version: 'v1.26.0'

          - name: Set Kube config
            uses: azure/k8s-set-context@v3
            with:
              method: kubeconfig
              kubeconfig: ${{secrets.KUBECONFIG}}

          - name: fetching the cluster details
            run: |
              kubectl version
              echo "----------------------------------"
              kubectl get nodes

          - name: Getting Ingress IP
            run: |
              echo "INGRESS_IP=$(kubectl get svc nginx -n app-routing-system -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

          - name: replace tokens in Manifest files
            uses: cschleiden/replace-tokens@v1
            with:
                tokenPrefix: '${'
                tokenSuffix: '}'
                files: '["kubernetes/development/*.yaml"]'
            env:
                NAMESPACE: ${{vars.NAMESPACE}}
                REPLICAS: ${{vars.REPLICAS}}
                K8S_IMAGE: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github['sha']}}
                INGRESS_IP: ${{env.INGRESS_IP}}

          - name: check files
            run: |
              cat kubernetes/development/*.yaml

