name: Solar System Workflow
on:
  workflow_dispatch: 
  push: 
    branches: ['main', 'feature/*']
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    Unit-Testing:
        strategy:
          matrix:
            os: [ubuntu-latest]
            version: [18,19,20]
            exclude:
              - version: '18'
        name: Unit-Testing
        runs-on: '${{matrix.os}}'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node Install
              uses: actions/setup-node@v4
              with:
                node-version: '${{matrix.version}}'

            - name: Caching the previous dependencies
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{runner.os}}_node_modules_${{hashFiles('package-lock.json')}}

            - name: Install dependence
              run: npm install

            - name: Unit Testing
              id: unit-testing
              run: npm test

            - name: Archeiving the artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: mocha-test-result
                overwrite: true
                path: test-results.xml

    code-coverage:
        name: Code-Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node Install
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Caching the previous dependencies
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{runner.os}}_node_modules_${{hashFiles('packages-lock.json')}}

            - name: Install dependence
              run: npm install

            - name: Check code Coverage
              run: npm run coverage
              continue-on-error: true

            - name: Archeiving the artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: code-coverage-result
                path: coverage
                overwrite: true
                retention-days: 5

    Docker:
        name: Containerization
        needs: [Unit-Testing, code-coverage]
        runs-on: ubuntu-latesT
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{vars.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Docker build for testing
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github['sha']}}

            - name: Docker image testing
              run: |
                docker images
                docker run --name=ss-app -d \
                  -p 3000:3000 \
                  -e MONGO_URI=$MONGO_URI \
                  -e MONGO_USERNAME=$MONGO_USERNAME \
                  -e MONGO_PASSWORD=$MONGO_PASSWORD \
                  ${{vars.DOCKERHUB_USERNAME}}/solar-system:${GITHUB_SHA}


                export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ss-app)
                echo $IP

                echo "testing Image url using wget"
                wget -q -O - 127.0.0.1:3000/live | grep -i 'live'
